//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComponentArt.Win.Demos.SoaNavBarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ComponentArt.SOA.UI", ConfigurationName="SoaNavBarService.ISoaNavBarService")]
    public interface ISoaNavBarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="ComponentArt.SOA.UI/ISoaNavBarService/GetItems", ReplyAction="ComponentArt.SOA.UI/ISoaNavBarService/GetItemsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaNavBarRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaNavBarItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaNavBarGetItemsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaNavBarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaNavBar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaNavBarGetItemsRequest))]
        ComponentArt.SOA.UI.SoaNavBarGetItemsResponse GetItems(ComponentArt.SOA.UI.SoaNavBarGetItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaNavBarService/GetItems", ReplyAction="ComponentArt.SOA.UI/ISoaNavBarService/GetItemsResponse")]
        System.IAsyncResult BeginGetItems(ComponentArt.SOA.UI.SoaNavBarGetItemsRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaNavBarGetItemsResponse EndGetItems(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISoaNavBarServiceChannel : ComponentArt.Win.Demos.SoaNavBarService.ISoaNavBarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaNavBarGetItemsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaNavBarGetItemsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SoaNavBarServiceClient : System.ServiceModel.ClientBase<ComponentArt.Win.Demos.SoaNavBarService.ISoaNavBarService>, ComponentArt.Win.Demos.SoaNavBarService.ISoaNavBarService {
        
        private BeginOperationDelegate onBeginGetItemsDelegate;
        
        private EndOperationDelegate onEndGetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onGetItemsCompletedDelegate;
        
        public SoaNavBarServiceClient() {
        }
        
        public SoaNavBarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoaNavBarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaNavBarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaNavBarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetItemsCompletedEventArgs> GetItemsCompleted;
        
        public ComponentArt.SOA.UI.SoaNavBarGetItemsResponse GetItems(ComponentArt.SOA.UI.SoaNavBarGetItemsRequest request) {
            return base.Channel.GetItems(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetItems(ComponentArt.SOA.UI.SoaNavBarGetItemsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetItems(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ComponentArt.SOA.UI.SoaNavBarGetItemsResponse EndGetItems(System.IAsyncResult result) {
            return base.Channel.EndGetItems(result);
        }
        
        private System.IAsyncResult OnBeginGetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaNavBarGetItemsRequest request = ((ComponentArt.SOA.UI.SoaNavBarGetItemsRequest)(inValues[0]));
            return this.BeginGetItems(request, callback, asyncState);
        }
        
        private object[] OnEndGetItems(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaNavBarGetItemsResponse retVal = this.EndGetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetItemsCompleted(object state) {
            if ((this.GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetItemsAsync(ComponentArt.SOA.UI.SoaNavBarGetItemsRequest request) {
            this.GetItemsAsync(request, null);
        }
        
        public void GetItemsAsync(ComponentArt.SOA.UI.SoaNavBarGetItemsRequest request, object userState) {
            if ((this.onBeginGetItemsDelegate == null)) {
                this.onBeginGetItemsDelegate = new BeginOperationDelegate(this.OnBeginGetItems);
            }
            if ((this.onEndGetItemsDelegate == null)) {
                this.onEndGetItemsDelegate = new EndOperationDelegate(this.OnEndGetItems);
            }
            if ((this.onGetItemsCompletedDelegate == null)) {
                this.onGetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginGetItemsDelegate, new object[] {
                        request}, this.onEndGetItemsDelegate, this.onGetItemsCompletedDelegate, userState);
        }
    }
}
