//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace ComponentArt.Silverlight.Demos.SoaComboBoxLocationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ComponentArt.SOA.UI", ConfigurationName="SoaComboBoxLocationService.ISoaComboBoxService")]
    public interface ISoaComboBoxService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaComboBoxService/Insert", ReplyAction="ComponentArt.SOA.UI/ISoaComboBoxService/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaComboBoxRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaComboBoxColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaComboBoxColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaComboBoxInsertResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaComboBoxResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaComboBoxSelectRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaComboBoxDataCondition>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaComboBoxDataCondition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaComboBoxDataConditionOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaComboBoxSelectResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<System.Collections.Generic.Dictionary<string, object>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        System.IAsyncResult BeginInsert(ComponentArt.SOA.UI.SoaComboBoxInsertRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaComboBoxInsertResponse EndInsert(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaComboBoxService/Select", ReplyAction="ComponentArt.SOA.UI/ISoaComboBoxService/SelectResponse")]
        System.IAsyncResult BeginSelect(ComponentArt.SOA.UI.SoaComboBoxSelectRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaComboBoxSelectResponse EndSelect(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISoaComboBoxServiceChannel : ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaComboBoxInsertResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaComboBoxInsertResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaComboBoxSelectResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaComboBoxSelectResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SoaComboBoxServiceClient : System.ServiceModel.ClientBase<ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService>, ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService {
        
        private BeginOperationDelegate onBeginInsertDelegate;
        
        private EndOperationDelegate onEndInsertDelegate;
        
        private System.Threading.SendOrPostCallback onInsertCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectDelegate;
        
        private EndOperationDelegate onEndSelectDelegate;
        
        private System.Threading.SendOrPostCallback onSelectCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SoaComboBoxServiceClient() {
        }
        
        public SoaComboBoxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoaComboBoxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaComboBoxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaComboBoxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<InsertCompletedEventArgs> InsertCompleted;
        
        public event System.EventHandler<SelectCompletedEventArgs> SelectCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService.BeginInsert(ComponentArt.SOA.UI.SoaComboBoxInsertRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsert(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaComboBoxInsertResponse ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService.EndInsert(System.IAsyncResult result) {
            return base.Channel.EndInsert(result);
        }
        
        private System.IAsyncResult OnBeginInsert(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaComboBoxInsertRequest request = ((ComponentArt.SOA.UI.SoaComboBoxInsertRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService)(this)).BeginInsert(request, callback, asyncState);
        }
        
        private object[] OnEndInsert(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaComboBoxInsertResponse retVal = ((ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService)(this)).EndInsert(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertCompleted(object state) {
            if ((this.InsertCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertCompleted(this, new InsertCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertAsync(ComponentArt.SOA.UI.SoaComboBoxInsertRequest request) {
            this.InsertAsync(request, null);
        }
        
        public void InsertAsync(ComponentArt.SOA.UI.SoaComboBoxInsertRequest request, object userState) {
            if ((this.onBeginInsertDelegate == null)) {
                this.onBeginInsertDelegate = new BeginOperationDelegate(this.OnBeginInsert);
            }
            if ((this.onEndInsertDelegate == null)) {
                this.onEndInsertDelegate = new EndOperationDelegate(this.OnEndInsert);
            }
            if ((this.onInsertCompletedDelegate == null)) {
                this.onInsertCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDelegate, new object[] {
                        request}, this.onEndInsertDelegate, this.onInsertCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService.BeginSelect(ComponentArt.SOA.UI.SoaComboBoxSelectRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelect(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaComboBoxSelectResponse ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService.EndSelect(System.IAsyncResult result) {
            return base.Channel.EndSelect(result);
        }
        
        private System.IAsyncResult OnBeginSelect(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaComboBoxSelectRequest request = ((ComponentArt.SOA.UI.SoaComboBoxSelectRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService)(this)).BeginSelect(request, callback, asyncState);
        }
        
        private object[] OnEndSelect(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaComboBoxSelectResponse retVal = ((ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService)(this)).EndSelect(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectCompleted(object state) {
            if ((this.SelectCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectCompleted(this, new SelectCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAsync(ComponentArt.SOA.UI.SoaComboBoxSelectRequest request) {
            this.SelectAsync(request, null);
        }
        
        public void SelectAsync(ComponentArt.SOA.UI.SoaComboBoxSelectRequest request, object userState) {
            if ((this.onBeginSelectDelegate == null)) {
                this.onBeginSelectDelegate = new BeginOperationDelegate(this.OnBeginSelect);
            }
            if ((this.onEndSelectDelegate == null)) {
                this.onEndSelectDelegate = new EndOperationDelegate(this.OnEndSelect);
            }
            if ((this.onSelectCompletedDelegate == null)) {
                this.onSelectCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectCompleted);
            }
            base.InvokeAsync(this.onBeginSelectDelegate, new object[] {
                        request}, this.onEndSelectDelegate, this.onSelectCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService CreateChannel() {
            return new SoaComboBoxServiceClientChannel(this);
        }
        
        private class SoaComboBoxServiceClientChannel : ChannelBase<ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService>, ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService {
            
            public SoaComboBoxServiceClientChannel(System.ServiceModel.ClientBase<ComponentArt.Silverlight.Demos.SoaComboBoxLocationService.ISoaComboBoxService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginInsert(ComponentArt.SOA.UI.SoaComboBoxInsertRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Insert", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaComboBoxInsertResponse EndInsert(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaComboBoxInsertResponse _result = ((ComponentArt.SOA.UI.SoaComboBoxInsertResponse)(base.EndInvoke("Insert", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelect(ComponentArt.SOA.UI.SoaComboBoxSelectRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Select", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaComboBoxSelectResponse EndSelect(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaComboBoxSelectResponse _result = ((ComponentArt.SOA.UI.SoaComboBoxSelectResponse)(base.EndInvoke("Select", _args, result)));
                return _result;
            }
        }
    }
}
