//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace ComponentArt.Silverlight.Demos.SoaDataGridMessageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ComponentArt.SOA.UI", ConfigurationName="SoaDataGridMessageService.ISoaDataGridService")]
    public interface ISoaDataGridService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaDataGridService/Delete", ReplyAction="ComponentArt.SOA.UI/ISoaDataGridService/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroupRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridDataCondition>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDataCondition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDataConditionOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridGrouping>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGrouping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaSortDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridInsertRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridInsertResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSelectRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridSorting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSorting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSelectResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridUpdateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridUpdateResponse))]
        System.IAsyncResult BeginDelete(ComponentArt.SOA.UI.SoaDataGridDeleteRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaDataGridDeleteResponse EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaDataGridService/Group", ReplyAction="ComponentArt.SOA.UI/ISoaDataGridService/GroupResponse")]
        System.IAsyncResult BeginGroup(ComponentArt.SOA.UI.SoaDataGridGroupRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaDataGridGroupResponse EndGroup(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaDataGridService/Insert", ReplyAction="ComponentArt.SOA.UI/ISoaDataGridService/InsertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDeleteRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroupRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridDataCondition>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDataCondition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDataConditionOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridGrouping>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGrouping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaSortDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridInsertResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSelectRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridSorting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSorting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSelectResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridUpdateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridUpdateResponse))]
        System.IAsyncResult BeginInsert(ComponentArt.SOA.UI.SoaDataGridInsertRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaDataGridInsertResponse EndInsert(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaDataGridService/Select", ReplyAction="ComponentArt.SOA.UI/ISoaDataGridService/SelectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDeleteRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroupRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridDataCondition>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDataCondition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDataConditionOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridGrouping>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGrouping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaSortDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridInsertRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridInsertResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSelectRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridSorting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSorting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridUpdateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridUpdateResponse))]
        System.IAsyncResult BeginSelect(ComponentArt.SOA.UI.SoaDataGridSelectRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaDataGridSelectResponse EndSelect(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaDataGridService/Update", ReplyAction="ComponentArt.SOA.UI/ISoaDataGridService/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<object>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDeleteRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroupRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridDataCondition>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDataCondition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridDataConditionOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridGrouping>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGrouping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaSortDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridInsertRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridInsertResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSelectRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaDataGridSorting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSorting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridSelectResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaDataGridUpdateResponse))]
        System.IAsyncResult BeginUpdate(ComponentArt.SOA.UI.SoaDataGridUpdateRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaDataGridUpdateResponse EndUpdate(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISoaDataGridServiceChannel : ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaDataGridDeleteResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaDataGridDeleteResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaDataGridGroupResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaDataGridGroupResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaDataGridInsertResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaDataGridInsertResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaDataGridSelectResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaDataGridSelectResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaDataGridUpdateResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaDataGridUpdateResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SoaDataGridServiceClient : System.ServiceModel.ClientBase<ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService>, ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService {
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGroupDelegate;
        
        private EndOperationDelegate onEndGroupDelegate;
        
        private System.Threading.SendOrPostCallback onGroupCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertDelegate;
        
        private EndOperationDelegate onEndInsertDelegate;
        
        private System.Threading.SendOrPostCallback onInsertCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectDelegate;
        
        private EndOperationDelegate onEndSelectDelegate;
        
        private System.Threading.SendOrPostCallback onSelectCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDelegate;
        
        private EndOperationDelegate onEndUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SoaDataGridServiceClient() {
        }
        
        public SoaDataGridServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoaDataGridServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaDataGridServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaDataGridServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<DeleteCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<GroupCompletedEventArgs> GroupCompleted;
        
        public event System.EventHandler<InsertCompletedEventArgs> InsertCompleted;
        
        public event System.EventHandler<SelectCompletedEventArgs> SelectCompleted;
        
        public event System.EventHandler<UpdateCompletedEventArgs> UpdateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.BeginDelete(ComponentArt.SOA.UI.SoaDataGridDeleteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaDataGridDeleteResponse ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaDataGridDeleteRequest request = ((ComponentArt.SOA.UI.SoaDataGridDeleteRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).BeginDelete(request, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaDataGridDeleteResponse retVal = ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(ComponentArt.SOA.UI.SoaDataGridDeleteRequest request) {
            this.DeleteAsync(request, null);
        }
        
        public void DeleteAsync(ComponentArt.SOA.UI.SoaDataGridDeleteRequest request, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        request}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.BeginGroup(ComponentArt.SOA.UI.SoaDataGridGroupRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGroup(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaDataGridGroupResponse ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.EndGroup(System.IAsyncResult result) {
            return base.Channel.EndGroup(result);
        }
        
        private System.IAsyncResult OnBeginGroup(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaDataGridGroupRequest request = ((ComponentArt.SOA.UI.SoaDataGridGroupRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).BeginGroup(request, callback, asyncState);
        }
        
        private object[] OnEndGroup(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaDataGridGroupResponse retVal = ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).EndGroup(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGroupCompleted(object state) {
            if ((this.GroupCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GroupCompleted(this, new GroupCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GroupAsync(ComponentArt.SOA.UI.SoaDataGridGroupRequest request) {
            this.GroupAsync(request, null);
        }
        
        public void GroupAsync(ComponentArt.SOA.UI.SoaDataGridGroupRequest request, object userState) {
            if ((this.onBeginGroupDelegate == null)) {
                this.onBeginGroupDelegate = new BeginOperationDelegate(this.OnBeginGroup);
            }
            if ((this.onEndGroupDelegate == null)) {
                this.onEndGroupDelegate = new EndOperationDelegate(this.OnEndGroup);
            }
            if ((this.onGroupCompletedDelegate == null)) {
                this.onGroupCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGroupCompleted);
            }
            base.InvokeAsync(this.onBeginGroupDelegate, new object[] {
                        request}, this.onEndGroupDelegate, this.onGroupCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.BeginInsert(ComponentArt.SOA.UI.SoaDataGridInsertRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsert(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaDataGridInsertResponse ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.EndInsert(System.IAsyncResult result) {
            return base.Channel.EndInsert(result);
        }
        
        private System.IAsyncResult OnBeginInsert(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaDataGridInsertRequest request = ((ComponentArt.SOA.UI.SoaDataGridInsertRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).BeginInsert(request, callback, asyncState);
        }
        
        private object[] OnEndInsert(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaDataGridInsertResponse retVal = ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).EndInsert(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertCompleted(object state) {
            if ((this.InsertCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertCompleted(this, new InsertCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertAsync(ComponentArt.SOA.UI.SoaDataGridInsertRequest request) {
            this.InsertAsync(request, null);
        }
        
        public void InsertAsync(ComponentArt.SOA.UI.SoaDataGridInsertRequest request, object userState) {
            if ((this.onBeginInsertDelegate == null)) {
                this.onBeginInsertDelegate = new BeginOperationDelegate(this.OnBeginInsert);
            }
            if ((this.onEndInsertDelegate == null)) {
                this.onEndInsertDelegate = new EndOperationDelegate(this.OnEndInsert);
            }
            if ((this.onInsertCompletedDelegate == null)) {
                this.onInsertCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDelegate, new object[] {
                        request}, this.onEndInsertDelegate, this.onInsertCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.BeginSelect(ComponentArt.SOA.UI.SoaDataGridSelectRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelect(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaDataGridSelectResponse ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.EndSelect(System.IAsyncResult result) {
            return base.Channel.EndSelect(result);
        }
        
        private System.IAsyncResult OnBeginSelect(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaDataGridSelectRequest request = ((ComponentArt.SOA.UI.SoaDataGridSelectRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).BeginSelect(request, callback, asyncState);
        }
        
        private object[] OnEndSelect(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaDataGridSelectResponse retVal = ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).EndSelect(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectCompleted(object state) {
            if ((this.SelectCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectCompleted(this, new SelectCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAsync(ComponentArt.SOA.UI.SoaDataGridSelectRequest request) {
            this.SelectAsync(request, null);
        }
        
        public void SelectAsync(ComponentArt.SOA.UI.SoaDataGridSelectRequest request, object userState) {
            if ((this.onBeginSelectDelegate == null)) {
                this.onBeginSelectDelegate = new BeginOperationDelegate(this.OnBeginSelect);
            }
            if ((this.onEndSelectDelegate == null)) {
                this.onEndSelectDelegate = new EndOperationDelegate(this.OnEndSelect);
            }
            if ((this.onSelectCompletedDelegate == null)) {
                this.onSelectCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectCompleted);
            }
            base.InvokeAsync(this.onBeginSelectDelegate, new object[] {
                        request}, this.onEndSelectDelegate, this.onSelectCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.BeginUpdate(ComponentArt.SOA.UI.SoaDataGridUpdateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaDataGridUpdateResponse ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService.EndUpdate(System.IAsyncResult result) {
            return base.Channel.EndUpdate(result);
        }
        
        private System.IAsyncResult OnBeginUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaDataGridUpdateRequest request = ((ComponentArt.SOA.UI.SoaDataGridUpdateRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).BeginUpdate(request, callback, asyncState);
        }
        
        private object[] OnEndUpdate(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaDataGridUpdateResponse retVal = ((ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService)(this)).EndUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateCompleted(object state) {
            if ((this.UpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateAsync(ComponentArt.SOA.UI.SoaDataGridUpdateRequest request) {
            this.UpdateAsync(request, null);
        }
        
        public void UpdateAsync(ComponentArt.SOA.UI.SoaDataGridUpdateRequest request, object userState) {
            if ((this.onBeginUpdateDelegate == null)) {
                this.onBeginUpdateDelegate = new BeginOperationDelegate(this.OnBeginUpdate);
            }
            if ((this.onEndUpdateDelegate == null)) {
                this.onEndUpdateDelegate = new EndOperationDelegate(this.OnEndUpdate);
            }
            if ((this.onUpdateCompletedDelegate == null)) {
                this.onUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDelegate, new object[] {
                        request}, this.onEndUpdateDelegate, this.onUpdateCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService CreateChannel() {
            return new SoaDataGridServiceClientChannel(this);
        }
        
        private class SoaDataGridServiceClientChannel : ChannelBase<ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService>, ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService {
            
            public SoaDataGridServiceClientChannel(System.ServiceModel.ClientBase<ComponentArt.Silverlight.Demos.SoaDataGridMessageService.ISoaDataGridService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDelete(ComponentArt.SOA.UI.SoaDataGridDeleteRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaDataGridDeleteResponse EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaDataGridDeleteResponse _result = ((ComponentArt.SOA.UI.SoaDataGridDeleteResponse)(base.EndInvoke("Delete", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGroup(ComponentArt.SOA.UI.SoaDataGridGroupRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Group", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaDataGridGroupResponse EndGroup(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaDataGridGroupResponse _result = ((ComponentArt.SOA.UI.SoaDataGridGroupResponse)(base.EndInvoke("Group", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsert(ComponentArt.SOA.UI.SoaDataGridInsertRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Insert", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaDataGridInsertResponse EndInsert(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaDataGridInsertResponse _result = ((ComponentArt.SOA.UI.SoaDataGridInsertResponse)(base.EndInvoke("Insert", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelect(ComponentArt.SOA.UI.SoaDataGridSelectRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Select", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaDataGridSelectResponse EndSelect(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaDataGridSelectResponse _result = ((ComponentArt.SOA.UI.SoaDataGridSelectResponse)(base.EndInvoke("Select", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdate(ComponentArt.SOA.UI.SoaDataGridUpdateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Update", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaDataGridUpdateResponse EndUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaDataGridUpdateResponse _result = ((ComponentArt.SOA.UI.SoaDataGridUpdateResponse)(base.EndInvoke("Update", _args, result)));
                return _result;
            }
        }
    }
}
