//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace ComponentArt.Silverlight.Demos.TreeViewFileBrowserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ComponentArt.SOA.UI", ConfigurationName="TreeViewFileBrowserService.ISoaTreeViewService")]
    public interface ISoaTreeViewService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaTreeViewService/DeleteNode", ReplyAction="ComponentArt.SOA.UI/ISoaTreeViewService/DeleteNodeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewNodeCheckBoxModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaTreeViewNode>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMultiSelectModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewCancelResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeView))]
        System.IAsyncResult BeginDeleteNode(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaTreeViewDeleteResponse EndDeleteNode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaTreeViewService/AddNode", ReplyAction="ComponentArt.SOA.UI/ISoaTreeViewService/AddNodeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewNodeCheckBoxModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaTreeViewNode>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMultiSelectModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewCancelResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeView))]
        System.IAsyncResult BeginAddNode(ComponentArt.SOA.UI.SoaTreeViewAddRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaTreeViewAddResponse EndAddNode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaTreeViewService/GetNodes", ReplyAction="ComponentArt.SOA.UI/ISoaTreeViewService/GetNodesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewNodeCheckBoxModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaTreeViewNode>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMultiSelectModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewCancelResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeView))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest))]
        System.IAsyncResult BeginGetNodes(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse EndGetNodes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaTreeViewService/MoveNode", ReplyAction="ComponentArt.SOA.UI/ISoaTreeViewService/MoveNodeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewNodeCheckBoxModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaTreeViewNode>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMultiSelectModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewCancelResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeView))]
        System.IAsyncResult BeginMoveNode(ComponentArt.SOA.UI.SoaTreeViewMoveRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaTreeViewMoveResponse EndMoveNode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="ComponentArt.SOA.UI/ISoaTreeViewService/EditNode", ReplyAction="ComponentArt.SOA.UI/ISoaTreeViewService/EditNodeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewNodeCheckBoxModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<ComponentArt.SOA.UI.SoaTreeViewNode>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMultiSelectModes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewDeleteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewCancelResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewAddResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewMoveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeViewEditResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComponentArt.SOA.UI.SoaTreeView))]
        System.IAsyncResult BeginEditNode(ComponentArt.SOA.UI.SoaTreeViewEditRequest request, System.AsyncCallback callback, object asyncState);
        
        ComponentArt.SOA.UI.SoaTreeViewEditResponse EndEditNode(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISoaTreeViewServiceChannel : ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DeleteNodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteNodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaTreeViewDeleteResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaTreeViewDeleteResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AddNodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddNodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaTreeViewAddResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaTreeViewAddResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetNodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MoveNodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MoveNodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaTreeViewMoveResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaTreeViewMoveResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EditNodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EditNodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComponentArt.SOA.UI.SoaTreeViewEditResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComponentArt.SOA.UI.SoaTreeViewEditResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SoaTreeViewServiceClient : System.ServiceModel.ClientBase<ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService>, ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService {
        
        private BeginOperationDelegate onBeginDeleteNodeDelegate;
        
        private EndOperationDelegate onEndDeleteNodeDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteNodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddNodeDelegate;
        
        private EndOperationDelegate onEndAddNodeDelegate;
        
        private System.Threading.SendOrPostCallback onAddNodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNodesDelegate;
        
        private EndOperationDelegate onEndGetNodesDelegate;
        
        private System.Threading.SendOrPostCallback onGetNodesCompletedDelegate;
        
        private BeginOperationDelegate onBeginMoveNodeDelegate;
        
        private EndOperationDelegate onEndMoveNodeDelegate;
        
        private System.Threading.SendOrPostCallback onMoveNodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditNodeDelegate;
        
        private EndOperationDelegate onEndEditNodeDelegate;
        
        private System.Threading.SendOrPostCallback onEditNodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SoaTreeViewServiceClient() {
        }
        
        public SoaTreeViewServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoaTreeViewServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaTreeViewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaTreeViewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<DeleteNodeCompletedEventArgs> DeleteNodeCompleted;
        
        public event System.EventHandler<AddNodeCompletedEventArgs> AddNodeCompleted;
        
        public event System.EventHandler<GetNodesCompletedEventArgs> GetNodesCompleted;
        
        public event System.EventHandler<MoveNodeCompletedEventArgs> MoveNodeCompleted;
        
        public event System.EventHandler<EditNodeCompletedEventArgs> EditNodeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.BeginDeleteNode(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteNode(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaTreeViewDeleteResponse ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.EndDeleteNode(System.IAsyncResult result) {
            return base.Channel.EndDeleteNode(result);
        }
        
        private System.IAsyncResult OnBeginDeleteNode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaTreeViewDeleteRequest request = ((ComponentArt.SOA.UI.SoaTreeViewDeleteRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).BeginDeleteNode(request, callback, asyncState);
        }
        
        private object[] OnEndDeleteNode(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaTreeViewDeleteResponse retVal = ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).EndDeleteNode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteNodeCompleted(object state) {
            if ((this.DeleteNodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteNodeCompleted(this, new DeleteNodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteNodeAsync(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest request) {
            this.DeleteNodeAsync(request, null);
        }
        
        public void DeleteNodeAsync(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest request, object userState) {
            if ((this.onBeginDeleteNodeDelegate == null)) {
                this.onBeginDeleteNodeDelegate = new BeginOperationDelegate(this.OnBeginDeleteNode);
            }
            if ((this.onEndDeleteNodeDelegate == null)) {
                this.onEndDeleteNodeDelegate = new EndOperationDelegate(this.OnEndDeleteNode);
            }
            if ((this.onDeleteNodeCompletedDelegate == null)) {
                this.onDeleteNodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteNodeCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteNodeDelegate, new object[] {
                        request}, this.onEndDeleteNodeDelegate, this.onDeleteNodeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.BeginAddNode(ComponentArt.SOA.UI.SoaTreeViewAddRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddNode(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaTreeViewAddResponse ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.EndAddNode(System.IAsyncResult result) {
            return base.Channel.EndAddNode(result);
        }
        
        private System.IAsyncResult OnBeginAddNode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaTreeViewAddRequest request = ((ComponentArt.SOA.UI.SoaTreeViewAddRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).BeginAddNode(request, callback, asyncState);
        }
        
        private object[] OnEndAddNode(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaTreeViewAddResponse retVal = ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).EndAddNode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddNodeCompleted(object state) {
            if ((this.AddNodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddNodeCompleted(this, new AddNodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddNodeAsync(ComponentArt.SOA.UI.SoaTreeViewAddRequest request) {
            this.AddNodeAsync(request, null);
        }
        
        public void AddNodeAsync(ComponentArt.SOA.UI.SoaTreeViewAddRequest request, object userState) {
            if ((this.onBeginAddNodeDelegate == null)) {
                this.onBeginAddNodeDelegate = new BeginOperationDelegate(this.OnBeginAddNode);
            }
            if ((this.onEndAddNodeDelegate == null)) {
                this.onEndAddNodeDelegate = new EndOperationDelegate(this.OnEndAddNode);
            }
            if ((this.onAddNodeCompletedDelegate == null)) {
                this.onAddNodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddNodeCompleted);
            }
            base.InvokeAsync(this.onBeginAddNodeDelegate, new object[] {
                        request}, this.onEndAddNodeDelegate, this.onAddNodeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.BeginGetNodes(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNodes(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.EndGetNodes(System.IAsyncResult result) {
            return base.Channel.EndGetNodes(result);
        }
        
        private System.IAsyncResult OnBeginGetNodes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest request = ((ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).BeginGetNodes(request, callback, asyncState);
        }
        
        private object[] OnEndGetNodes(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse retVal = ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).EndGetNodes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNodesCompleted(object state) {
            if ((this.GetNodesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNodesCompleted(this, new GetNodesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNodesAsync(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest request) {
            this.GetNodesAsync(request, null);
        }
        
        public void GetNodesAsync(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest request, object userState) {
            if ((this.onBeginGetNodesDelegate == null)) {
                this.onBeginGetNodesDelegate = new BeginOperationDelegate(this.OnBeginGetNodes);
            }
            if ((this.onEndGetNodesDelegate == null)) {
                this.onEndGetNodesDelegate = new EndOperationDelegate(this.OnEndGetNodes);
            }
            if ((this.onGetNodesCompletedDelegate == null)) {
                this.onGetNodesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNodesCompleted);
            }
            base.InvokeAsync(this.onBeginGetNodesDelegate, new object[] {
                        request}, this.onEndGetNodesDelegate, this.onGetNodesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.BeginMoveNode(ComponentArt.SOA.UI.SoaTreeViewMoveRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMoveNode(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaTreeViewMoveResponse ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.EndMoveNode(System.IAsyncResult result) {
            return base.Channel.EndMoveNode(result);
        }
        
        private System.IAsyncResult OnBeginMoveNode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaTreeViewMoveRequest request = ((ComponentArt.SOA.UI.SoaTreeViewMoveRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).BeginMoveNode(request, callback, asyncState);
        }
        
        private object[] OnEndMoveNode(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaTreeViewMoveResponse retVal = ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).EndMoveNode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMoveNodeCompleted(object state) {
            if ((this.MoveNodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MoveNodeCompleted(this, new MoveNodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MoveNodeAsync(ComponentArt.SOA.UI.SoaTreeViewMoveRequest request) {
            this.MoveNodeAsync(request, null);
        }
        
        public void MoveNodeAsync(ComponentArt.SOA.UI.SoaTreeViewMoveRequest request, object userState) {
            if ((this.onBeginMoveNodeDelegate == null)) {
                this.onBeginMoveNodeDelegate = new BeginOperationDelegate(this.OnBeginMoveNode);
            }
            if ((this.onEndMoveNodeDelegate == null)) {
                this.onEndMoveNodeDelegate = new EndOperationDelegate(this.OnEndMoveNode);
            }
            if ((this.onMoveNodeCompletedDelegate == null)) {
                this.onMoveNodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMoveNodeCompleted);
            }
            base.InvokeAsync(this.onBeginMoveNodeDelegate, new object[] {
                        request}, this.onEndMoveNodeDelegate, this.onMoveNodeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.BeginEditNode(ComponentArt.SOA.UI.SoaTreeViewEditRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditNode(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComponentArt.SOA.UI.SoaTreeViewEditResponse ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService.EndEditNode(System.IAsyncResult result) {
            return base.Channel.EndEditNode(result);
        }
        
        private System.IAsyncResult OnBeginEditNode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComponentArt.SOA.UI.SoaTreeViewEditRequest request = ((ComponentArt.SOA.UI.SoaTreeViewEditRequest)(inValues[0]));
            return ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).BeginEditNode(request, callback, asyncState);
        }
        
        private object[] OnEndEditNode(System.IAsyncResult result) {
            ComponentArt.SOA.UI.SoaTreeViewEditResponse retVal = ((ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService)(this)).EndEditNode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEditNodeCompleted(object state) {
            if ((this.EditNodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditNodeCompleted(this, new EditNodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditNodeAsync(ComponentArt.SOA.UI.SoaTreeViewEditRequest request) {
            this.EditNodeAsync(request, null);
        }
        
        public void EditNodeAsync(ComponentArt.SOA.UI.SoaTreeViewEditRequest request, object userState) {
            if ((this.onBeginEditNodeDelegate == null)) {
                this.onBeginEditNodeDelegate = new BeginOperationDelegate(this.OnBeginEditNode);
            }
            if ((this.onEndEditNodeDelegate == null)) {
                this.onEndEditNodeDelegate = new EndOperationDelegate(this.OnEndEditNode);
            }
            if ((this.onEditNodeCompletedDelegate == null)) {
                this.onEditNodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditNodeCompleted);
            }
            base.InvokeAsync(this.onBeginEditNodeDelegate, new object[] {
                        request}, this.onEndEditNodeDelegate, this.onEditNodeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService CreateChannel() {
            return new SoaTreeViewServiceClientChannel(this);
        }
        
        private class SoaTreeViewServiceClientChannel : ChannelBase<ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService>, ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService {
            
            public SoaTreeViewServiceClientChannel(System.ServiceModel.ClientBase<ComponentArt.Silverlight.Demos.TreeViewFileBrowserService.ISoaTreeViewService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDeleteNode(ComponentArt.SOA.UI.SoaTreeViewDeleteRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("DeleteNode", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaTreeViewDeleteResponse EndDeleteNode(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaTreeViewDeleteResponse _result = ((ComponentArt.SOA.UI.SoaTreeViewDeleteResponse)(base.EndInvoke("DeleteNode", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddNode(ComponentArt.SOA.UI.SoaTreeViewAddRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AddNode", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaTreeViewAddResponse EndAddNode(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaTreeViewAddResponse _result = ((ComponentArt.SOA.UI.SoaTreeViewAddResponse)(base.EndInvoke("AddNode", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNodes(ComponentArt.SOA.UI.SoaTreeViewGetNodesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetNodes", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse EndGetNodes(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse _result = ((ComponentArt.SOA.UI.SoaTreeViewGetNodesResponse)(base.EndInvoke("GetNodes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginMoveNode(ComponentArt.SOA.UI.SoaTreeViewMoveRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("MoveNode", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaTreeViewMoveResponse EndMoveNode(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaTreeViewMoveResponse _result = ((ComponentArt.SOA.UI.SoaTreeViewMoveResponse)(base.EndInvoke("MoveNode", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEditNode(ComponentArt.SOA.UI.SoaTreeViewEditRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("EditNode", _args, callback, asyncState);
                return _result;
            }
            
            public ComponentArt.SOA.UI.SoaTreeViewEditResponse EndEditNode(System.IAsyncResult result) {
                object[] _args = new object[0];
                ComponentArt.SOA.UI.SoaTreeViewEditResponse _result = ((ComponentArt.SOA.UI.SoaTreeViewEditResponse)(base.EndInvoke("EditNode", _args, result)));
                return _result;
            }
        }
    }
}
