using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Windows;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitle("ComponentArt.Win.UI.ComponentArt.Win.Demos.Xbap")]
[assembly: AssemblyCompany("ComponentArt")]
[assembly: AssemblyCopyright("Copyright 2011, ComponentArt")]
[assembly: AssemblyVersion("2012.1.1016.35")]
[assembly: AllowPartiallyTrustedCallers()]
[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]

