using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Web.UI;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitle("ComponentArt.Web.Visualization.Gauges")]
[assembly: AssemblyCompany("ComponentArt")]
[assembly: AssemblyCopyright("Copyright 2011, ComponentArt")]
[assembly: AssemblyVersion("2012.1.1016.2")]
[assembly: AllowPartiallyTrustedCallers()]


[assembly: WebResourceAttribute("ComponentArt.Web.Visualization.Gauges.client_scripts.A654u.js", "text/javascript")]
[assembly: WebResourceAttribute("ComponentArt.Web.Visualization.Gauges.client_scripts.A654k.js", "text/javascript")]